[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.mysqli"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader || echo 'No composer dependencies'"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."
